workspace/config/routes.rb
Rails.application.routes.draw do

  root 'jazz#index'
  get 'info' => 'jazz#info'
  get 'resources' => 'jazz#resources'
  get 'artists' => 'jazz#artists'
  post 'mailer' => 'jazz#mailer'

end

workspace/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

workspace/app/controllers/jazz_controller.rb
class JazzController < ApplicationController
    
    def index
    end
    
    def info
    end
    
    def resources
    end
    
    def artists
    end

    def mailer
        em = '"' + params[:email] + '"'
        sub = '"' + params[:subject] + '"'
        msg = '"' + params[:message] + '"'
        file = File.join(Rails.root, 'app', 'assets', 'scripts', 'mailer.pl')
        path = "#{File.absolute_path(file)}"
        cmd = `perl #{path} #{em} #{sub} #{msg}`
        puts cmd
        if cmd.eql? 'true'
            render :inline => "<div class='alert alert-success'>
                                <strong>Your message has been sent!</strong>
                              </div>".html_safe
        elsif cmd.eql? 'error'
            render :inline => "<div class='alert alert-danger'>
                                <strong>Please review the form and fill in all fields.</strong>
                              </div>".html_safe
        elsif cmd.eql? 'emailError'
            render :inline => "<div class='alert alert-danger'>
                                <strong>Please enter a vaild email.</strong>
                              </div>".html_safe
        else
            render :inline => "<div class='alert alert-danger'>
                                <strong>There was a problem! Try again later or try emailing djfearon0@frostburg.edu using another service.</strong>
                              </div>".html_safe
        end
    end

end

workspace/app/helpers/application_helper.rb
module ApplicationHelper
end

workspace/app/helpers/jazz_helper.rb
module JazzHelper
end

workspace/app/views/jazz/artists.html.erb
<div class="page">
    <div class="pageContent">

      <h1 class="title">Famous Artists</h1>


      <div id="artistList">
        <ul id="links">
          <li><a href="javascript:getBio('Julian Edwin Adderley');">Cannonball Adderley</a></li>
          <li><a href="javascript:getBio('Benny Carter');">Benny Carter</a></li>
          <li><a href="javascript:getBio('John Coltrane');">John Coltrane</a></li>
          <li><a href="javascript:getBio('Dexter Gordon');">Dexter Gordon</a></li>
          <li><a href="javascript:getBio('Kenneth Bruce Gorelick');">Kenny G</a></li>
          <li><a href="javascript:getBio('Woody Herman');">Woody Herman</a></li>
          <li><a href="javascript:getBio('Johnny Hodges');">Johnny Hodges</a></li>
          <li><a href="javascript:getBio('Charlie Parker');">Charlie Parker</a></li>
          <li><a href="javascript:getBio('Sonny Rollins');">Sonny Rollins</a></li>
          <li><a href="javascript:getBio('Lester Young');">Lester Young</a></li>
        </ul>
      </div>


      <div id="artistContent">
        <div>
          <div id="image"></div>
        </div>
        <div class="artistInfo">
          <strong>Name: </strong>
          <p>
            <div id="name"></div>
          </p>
        </div>
        <div class="artistInfo">
          <strong>Nicknames: </strong>
          <p>
          <div id="nicknames"></div>
          </p>
        </div>
        <div class="artistInfo">
          <strong>Born: </strong>
          <p>
            <div id="birth"></div>
          </p>
          <strong>Died: </strong>
          <p>
            <div id="death"></div>
          </p>
        </div>
        <div class="artistInfo">
          <strong>Bio: </strong>
          <p>
            <div id="bio"></div>
          </p>
        </div>
        <div class="artistInfo">
          <strong>More Info: </strong>
          <p>
          <div id="url"></div>
          </p>
        </div>
      </div>

    </div>
</div>

<script>
  $( document ).ready( getBio("Julian Edwin Adderley") );
</script>

<!--

  Bibliography

  Cannonball Adderley. Bio.com. Accessed June 06, 2016. http://www.biography.com/people/cannonball-adderley-9176317
  Benny Carter. Bio.com. Accessed June 22, 2016. http://www.biography.com/people/benny-carter-9239852
  John Coltrane. Bio.com. Accessed June 06, 2016. http://www.biography.com/people/john-coltrane-9254106
  Kenny G. Bio.com. Accessed June 22, 2016. http://www.biography.com/people/kenny-g-21212793
  Dexter Gordon. Bio.com. Accessed June 22, 2016. http://www.biography.com/people/dexter-gordon-37899
  Woody Herman. Bio.com. Accessed June 22, 2016. http://www.biography.com/people/woody-herman-9336339
  Johnny Hodges. Bio.com. Accessed June 22, 2016. http://www.biography.com/people/johnny-hodges-9340825
  Charlie Parker. Bio.com. Accessed June 06, 2016. http://www.biography.com/people/charlie-parker-9433413
  Sonny Rollins. Bio.com. Accessed June 22, 2016. http://www.biography.com/people/sonny-rollins-9462811
  Lester Young. Bio.com. Accessed June 22, 2016. http://www.biography.com/people/lester-young-9539541


  Images

  Cannonball Adderley. AllMusic.com. Accessed June 22, 2016. http://www.allmusic.com/artist/cannonball-adderley-mn0000548338
  Benny Carter. Wikipedia.com. Accessed June 24, 2016. https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Benny_Carter.jpg/330px-Benny_Carter.jpg
  John Coltrane. Wikipedia.com. Accessed June 24, 2016. https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/John_Coltrane_1963.jpg/330px-John_Coltrane_1963.jpg
  Kenny G. Wikipedia.com. Accessed June 24, 2016. https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/KennyGHWOFMay2013.jpg/330px-KennyGHWOFMay2013.jpg
  Dexter Gordon. Wikipedia.com. Accessed June 24, 2016. https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Dexter_Gordon1.jpg/330px-Dexter_Gordon1.jpg
  Woody Herman. Wikipedia.com. Accessed June 24, 2016. https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Woody_Herman_1949.JPG/330px-Woody_Herman_1949.JPG
  Johnny Hodges. Wikipedia.com. Accessed June 24, 2016. https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Johnny_Hodges_and_Al_Sears%2C_Aquarium%2C_New_York%2C%2C_ca._Nov._1946_%28William_P._Gottlieb_04191%29.jpg/330px-Johnny_Hodges_and_Al_Sears%2C_Aquarium%2C_New_York%2C%2C_ca._Nov._1946_%28William_P._Gottlieb_04191%29.jpg
  Charlie Parker. Wikipedia.com. Accessed June 24, 2016. https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Charlie_Parker%2C_Tommy_Potter%2C_Miles_Davis%2C_Max_Roach_%28Gottlieb_06941%29.jpg/330px-Charlie_Parker%2C_Tommy_Potter%2C_Miles_Davis%2C_Max_Roach_%28Gottlieb_06941%29.jpg
  Sonny Rollins. Wikipedia.com. Accessed June 24, 2016. https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Sonny_Rollins_2011.jpg/330px-Sonny_Rollins_2011.jpg
  Lester Young. Wikipedia.com. Accessed June 24, 2016. https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Lester-Young-LIFE-1944.jpg/330px-Lester-Young-LIFE-1944.jpg

-->

workspace/app/views/jazz/index.html.erb
<div class="page">
    <div class="pageContent">
        <h1 class="title">Greetings visitors, fellow saxophonists, and curious minds</h1>
        <p>
            Thank you for visiting Jazz Saxophones! This site will give you some insight into the world of jazz saxophonists.
            Take a look through some of the history by visiting the "Artists" section. There you will find information about
            a number of famous jazz saxophonists over the years. Check out our "Player's Resources" to get ahold of some practice
            materials and audio helpers. Finally, head on over to "Information for Sax Owners" to learn some tips about the care and
            maintenance of your horn.
        </p>
        <%= image_tag "630_Logo_Large.png", id: "logo-large"%>
    </div>
</div>

workspace/app/views/jazz/info.html.erb
<div class="page">
    <div class="pageContent">
        <h1 class="title">Information for Sax Owners</h1>
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h3>Whoops! There isn't any content here!</h3>
          </div>
          <div class="panel-body">
            <h4>
              We're terribly sorry, but there isn't any content on this page.
              The content for this page was going to be implemented in PHP, but it turns out that it
              doesn't play nicely with Ruby on Rails. This page can be viewed in the PHP-based project named
              "djfearon0_cosc630_php_example".
            </h4>
          </div>
        </div>
    </div>
</div>

workspace/app/views/jazz/resources.html.erb
<div class="page">
    <div class="pageContent">
        <h1 class="title">Player's Resources</h1>
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h3>Whoops! There isn't any content here!</h3>
          </div>
          <div class="panel-body">
            <h4>
              We're terribly sorry, but there isn't any content on this page.
              The content for this page was going to be implemented in Python, but it turns out that it
              doesn't play nicely with Ruby on Rails. This page can be viewed in the Python-based project named
              "djfearon0_cosc630_python_example".
            </h4>
          </div>
        </div>
    </div>
</div>

workspace/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Jazzophones</title>
  <%=stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track'=> true %>
    <%=javascript_include_tag 'application', 'data-turbolinks-track'=> true %>
      <%=csrf_meta_tags %>
</head>

<body>
  <div id="navbar-container">
    <nav id-="navbar" class="navbar navbar-inverse" role="navigation">
        <div id="nav-item-container" class="container-fluid">
          <%= link_to root_path do %>
            <%= image_tag "630_Logo.png", class: "navbar-brand", id: "logo"%>
          <% end %>
          <ul class="nav navbar-nav">
            <li role="presentation">
              <%= link_to '<i class="glyphicon glyphicon-home tab-link"></i> Home'.html_safe, root_path %>
            </li>
            <li role="presentation">
              <%= link_to '<i class="glyphicon glyphicon-music tab-link"></i> Famous Saxophonists'.html_safe, artists_path %>
            </li>
            <li role="presentation">
              <%= link_to '<i class="glyphicon glyphicon-arrow-down tab-link"></i> Player\'s Resources'.html_safe,  resources_path %>
            </li>
            <li role="presentation">
              <%= link_to '<i class="glyphicon glyphicon-info-sign tab-link"></i> Information for Sax Owners'.html_safe, info_path %>
            </li>
          </ul>
        </div>
        <div id="navbar-small" class="btn-group">
          <button id="navButton" class="btn dropdown-toggle glyphicon glyphicon-menu-hamburger" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

          </button>
          <ul class="dropdown-menu">
            <li role="presentation">
              <%= link_to '<i class="glyphicon glyphicon-home tab-link-small"></i> Home'.html_safe, root_path %>
            </li>
            <li role="presentation">
              <%= link_to '<i class="glyphicon glyphicon-music tab-link-small"></i> Famous Saxophonists'.html_safe, artists_path %>
            </li>
            <li role="presentation">
              <%= link_to '<i class="glyphicon glyphicon-arrow-down tab-link-small"></i> Player\'s Resources'.html_safe,  resources_path %>
            </li>
            <li role="presentation">
              <%= link_to '<i class="glyphicon glyphicon-info-sign tab-link-small"></i> Information for Sax Owners'.html_safe, info_path %>
            </li>
          </ul>
          <%= link_to root_path do %>
            <%= image_tag "630_Logo.png", class: "navbar-brand", id: "logo-small"%>
          <% end %>
        </div>
    </nav>
  </div>

  <div id="content" class="container-fluid">
    <%=yield %>
  </div>


  <div id="mailer" class="footer navbar-fixed-bottom navbar-inverse">
    <div class="container-fluid">
      <h4 id="contact">Questions, comments, or concerns? To contact the owner of this site, <a href="#" data-target="#mailerModal" data-toggle="modal">click here</a>.</h4>
    </div>
  </div>

  <div id="mailerModal" class="modal fade" data-backdrop="static">
    <div class="modal-content">
      <div class="modal-header">
        <button onclick="clearForm();" type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span area-hidden="true">&times;</span>
        </button>
      </div>
      <div id="notifications"></div> <!--Empty div for email confirmation -->
      <div class="modal-body">
        <form id="mailForm">
          <span class="formLabel">Your Email:</span>
          <input id="mailTo" type="text" class="mailInput"></input>
          <span class="formLabel">Subject:</span>
          <input id="mailSubject" type="text" class="mailInput"></input>
          <span class="formLabel">Message:</span>
          <textarea id="mailBody" class="mailInput"></textarea>
        </form>
      </div>
      <div class="modal-footer">
        <button onclick="mailer();" type="button" class="btn btn-primary" form="mailForm">Send Message</button>
        <button onclick="clearForm();" type="button" class="btn btn-danger" data-target="#mailerModal" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>

</body>

</html>